include: expose a copy of nf_conntrack_common.h
Get rid of copy&paster definitions that were made long time ago, this is
causing problems.

Copy and rename nf_conntrack_common.h to linux_nf_conntrack_common.h,
then include it from libnetfilter_conntrack.h

After that change, we can remove the status flags definition in
libnetfilter_conntrack.h that was copied and pasted from the above file.

This helps us solve compilation errors due to redeclaration:

 /usr/include/libnetfilter_conntrack/libnetfilter_conntrack.h:729:6: error: redeclaration of ‘enum ip_conntrack_status’
 In file included from nf-log.c:12:0: /usr/include/linux/netfilter/nf_conntrack_common.h:37:6: note: originally defined here

Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>